### ISSUE TITLE
Declare sensor 

### ISSUE THREAD

**Issue by fbarth75** [frtz13/EnergyRouter#2]
hi how to declare this sensor for the apexchart card ?
 - entity: sensor.house_real_power
 
Thanks for your work

**Comment by frtz13** [comment]
you can do it this way:
```mqtt:
    sensor:
      - name: "House Real Power"
        state_topic: "shellies/fusebox/emeter/0/power"
        unit_of_measurement: 'W'
        value_template: "{{ value | round(0) }}"
        device_class: "power"
        expire_after: 65
```

**Comment by fbarth75** [comment]
> you can do it this way:
> 
> ```
>     sensor:
>       - name: "House Real Power"
>         state_topic: "shellies/fusebox/emeter/0/power"
>         unit_of_measurement: 'W'
>         value_template: "{{ value | round(0) }}"
>         device_class: "power"
>         expire_after: 65
> ```

Thanks you , i used data from my enphase gateway , is this value result from cons-prod ? so this number can be negative ?

**Comment by frtz13** [comment]
yes. positive when the household consumes power. negative when production greater than consumption.
the value should be updated frequently, say every couple of seconds, or even faster.

**Comment by fbarth75** [comment]
> yes. positive when the household consumes power. negative when production greater than consumption. the value should be updated frequently, say every couple of seconds, or even faster.

Ok i think i'm good with my settings , i'll see tomorrow when i get some production , my data is return every 2 seconds from a node red flow , thanks for your help ;)
