### ISSUE TITLE
Little mistake in the code

### ISSUE THREAD

**Issue by fbarth75** [frtz13/EnergyRouter#3]
I find a mistake in your code: 
switch:
      - name: "Energy router mode auto"
        state_topic: "home/**solarheat**-dimmer/mode"
        value_template: >
          {%- if int(value) == -1 -%}ON{%- else -%}OFF{%- endif -%}
        availability:
          - topic: "home/waterheater-dimmer/RouterLWT"
            payload_available: "online"
            payload_not_available: "offline"
        state_on: "ON"
        state_off: "OFF"
        command_topic: "home/waterheater-dimmer/mode"
        payload_on: -1
        payload_off: 0
        optimistic: false
        qos: 0
        retain: true
        icon: mdi:routes

That doesn't work , we need to change solarheat with waterheater and it's work

**Comment by frtz13** [comment]
... thanks. fixed it.
